# Generated by Django 5.2.3 on 2025-07-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ZutoPages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_index",
                    models.IntegerField(
                        choices=[
                            (0, "novel"),
                            (1, "poem"),
                            (2, "music"),
                            (3, "game"),
                            (4, "movie"),
                            (5, "performance"),
                            (6, "animation"),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("cover_image", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
