# Generated by Django 5.2.3 on 2025-07-08 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ZutoPages", "0002_work"),
    ]

    operations = [
        migrations.CreateModel(
            name="Write",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("views", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("parentID", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ZutoPages.user"
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ZutoPages.work"
                    ),
                ),
            ],
        ),
    ]
