# Generated by Django 5.2.3 on 2025-07-08 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ZutoPages", "0003_write"),
    ]

    operations = [
        migrations.CreateModel(
            name="WriteLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ZutoPages.user"
                    ),
                ),
                (
                    "write",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ZutoPages.write",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "write")},
            },
        ),
    ]
